### ISSUE TITLE
问完问题可以搜索但是没有回答

### ISSUE THREAD

**Issue by zhuyi10822** [Steven-Luo/AISearchQA#1]
PS E:\合肥人工智能院实习文件\任务\6.7\任务2\AISearchQA-main> sh start.sh                              
D:\Python\Python39\lib\site-packages\langchain\_api\module_import.py:92: LangChainDeprecationWarning: Importing Chroma from langchain.vectorstores is deprecated. Please replace deprecated imports:

>> from langchain.vectorstores import Chroma

with new imports of:

>> from langchain_community.vectorstores import Chroma
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here https://python.langchain.com/v0.2/docs/versions/v0_2/
  warn_deprecated(
2024-06-11 16:52:39 - Your app is available at http://localhost:8000
2024-06-11 16:52:41 - Translated markdown file for zh-CN not found. Defaulting to chainlit.md.
获取网页全文:  10%|██████████████████                                                                                                                                                                   | 1/10 [00:00<00:01,  6.87it/s]h
ttps://www.aigc.cn/large-models, 'gb18030' codec can't decode byte 0x80 in position 794: illegal multibyte sequence
获取网页全文:  30%|██████████████████████████████████████████████████████▎                                                                                                                              | 3/10 [00:00<00:01,  6.73it/s]h
ttp://ai.ruc.edu.cn/research/science/20230605100.html, 'gb18030' codec can't decode byte 0x80 in position 545: illegal multibyte sequence
获取网页全文:  50%|██████████████████████████████████████████████████████████████████████████████████████████▌                                                                                          | 5/10 [00:00<00:00,  8.05it/s]h
ttps://www.ibm.com/cn-zh/topics/large-language-models, 'gb18030' codec can't decode byte 0x80 in position 241: illegal multibyte sequence
获取网页全文:  60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                        | 6/10 [00:01<00:00,  4.59it/s]h
ttps://baike.baidu.com/item/%E5%A4%A7%E8%AF%AD%E8%A8%80%E6%A8%A1%E5%9E%8B/62884793, 'gb18030' codec can't decode byte 0x80 in position 165: illegal multibyte sequence
获取网页全文:  70%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                      | 7/10 [00:01<00:00,  4.77it/s]h
ttps://github.com/LLMBook-zh/LLMBook-zh.github.io, 'gb18030' codec can't decode byte 0x80 in position 13364: illegal multibyte sequence
获取网页全文:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                    | 8/10 [00:02<00:00,  2.05it/s]h
ttp://ai.ruc.edu.cn/research/science/20240426001.html, 'gb18030' codec can't decode byte 0x80 in position 2403: illegal multibyte sequence
https://intro-llm.github.io/, 'gb18030' codec can't decode byte 0x80 in position 169: illegal multibyte sequence
获取网页全文: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.58it/s]
2024-06-11 16:52:59 - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
D:\Python\Python39\lib\site-packages\langchain_core\_api\deprecation.py:119: LangChainDeprecationWarning: The method `BaseRetriever.get_relevant_documents` was deprecated in langchain-core 0.1.46 and will be removed in 0.3.0. Use in
voke instead.
  warn_deprecated(
大语言模型综述 - Renmin University of China
大语言模型综述 - Renmin University of China
GitHub - LLMBook-zh/LLMBook-zh.github.io: 《大语言模型 ...
大规模语言模型：从理论到实践 - GitHub Pages

**Comment by Steven-Luo** [comment]
> PS E:\合肥人工智能院实习文件\任务\6.7\任务2\AISearchQA-main> sh start.sh D:\Python\Python39\lib\site-packages\langchain_api\module_import.py:92: LangChainDeprecationWarning: Importing Chroma from langchain.vectorstores is deprecated. Please replace deprecated imports:
> 
> > > from langchain.vectorstores import Chroma
> 
> with new imports of:
> 
> > > from langchain_community.vectorstores import Chroma
> > > You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here https://python.langchain.com/v0.2/docs/versions/v0_2/
> > > warn_deprecated(
> > > 2024-06-11 16:52:39 - Your app is available at http://localhost:8000
> > > 2024-06-11 16:52:41 - Translated markdown file for zh-CN not found. Defaulting to chainlit.md.
> > > 获取网页全文:  10%|██████████████████                                                                                                                                                                   | 1/10 [00:00<00:01,  6.87it/s]h
> > > ttps://www.aigc.cn/large-models, 'gb18030' codec can't decode byte 0x80 in position 794: illegal multibyte sequence
> > > 获取网页全文:  30%|██████████████████████████████████████████████████████▎                                                                                                                              | 3/10 [00:00<00:01,  6.73it/s]h
> > > ttp://ai.ruc.edu.cn/research/science/20230605100.html, 'gb18030' codec can't decode byte 0x80 in position 545: illegal multibyte sequence
> > > 获取网页全文:  50%|██████████████████████████████████████████████████████████████████████████████████████████▌                                                                                          | 5/10 [00:00<00:00,  8.05it/s]h
> > > ttps://www.ibm.com/cn-zh/topics/large-language-models, 'gb18030' codec can't decode byte 0x80 in position 241: illegal multibyte sequence
> > > 获取网页全文:  60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                        | 6/10 [00:01<00:00,  4.59it/s]h
> > > ttps://baike.baidu.com/item/%E5%A4%A7%E8%AF%AD%E8%A8%80%E6%A8%A1%E5%9E%8B/62884793, 'gb18030' codec can't decode byte 0x80 in position 165: illegal multibyte sequence
> > > 获取网页全文:  70%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                      | 7/10 [00:01<00:00,  4.77it/s]h
> > > ttps://github.com/LLMBook-zh/LLMBook-zh.github.io, 'gb18030' codec can't decode byte 0x80 in position 13364: illegal multibyte sequence
> > > 获取网页全文:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                    | 8/10 [00:02<00:00,  2.05it/s]h
> > > ttp://ai.ruc.edu.cn/research/science/20240426001.html, 'gb18030' codec can't decode byte 0x80 in position 2403: illegal multibyte sequence
> > > https://intro-llm.github.io/, 'gb18030' codec can't decode byte 0x80 in position 169: illegal multibyte sequence
> > > 获取网页全文: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.58it/s]
> > > 2024-06-11 16:52:59 - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
> > > D:\Python\Python39\lib\site-packages\langchain_core_api\deprecation.py:119: LangChainDeprecationWarning: The method `BaseRetriever.get_relevant_documents` was deprecated in langchain-core 0.1.46 and will be removed in 0.3.0. Use in
> > > voke instead.
> > > warn_deprecated(
> > > 大语言模型综述 - Renmin University of China
> > > 大语言模型综述 - Renmin University of China
> > > GitHub - LLMBook-zh/LLMBook-zh.github.io: 《大语言模型 ...
> > > 大规模语言模型：从理论到实践 - GitHub Pages

你好，已经把解决方案更新到FAQ中，请尝试
